# Generated by Django 4.2.7 on 2023-12-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobapplications_jobbooking_rename_type_jobs_job_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job_id',
        ),
    ]
