# Generated by Django 4.2.7 on 2023-12-13 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_employee_id_jobapplications_worker_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbooking',
            name='booked_date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.FileField(default=1, upload_to='jobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_details',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.FileField(upload_to='userprofile'),
        ),
    ]
