# Generated by Django 4.2.7 on 2023-12-13 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobbooking_booked_date_jobs_image_jobs_job_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbooking',
            name='worker_id',
        ),
        migrations.CreateModel(
            name='WorkerJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jobs')),
                ('worker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='WorkerJob_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_booking', to='app.workerjobs'),
        ),
    ]
