# Generated by Django 4.2.7 on 2024-01-05 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_jobbooking_worker_id_workerjobs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='worker_id',
        ),
        migrations.RemoveField(
            model_name='workerjobs',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='workerjobs',
            name='worker_id',
        ),
        migrations.RemoveField(
            model_name='jobapplications',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='booked_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=50),
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='JobCategory',
        ),
        migrations.DeleteModel(
            name='JobBooking',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='WorkerJobs',
        ),
        migrations.AddField(
            model_name='job',
            name='jobcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobcategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.job'),
            preserve_default=False,
        ),
    ]
