# Generated by Django 4.2.7 on 2024-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_job_remove_reviews_employer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
