# Generated by Django 4.2.7 on 2024-01-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_job_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='worker_id',
            new_name='employer_id',
        ),
    ]
